version: '3.9'

services:
  user-postgres:
    image: postgres:latest
    ports:
      - '6543:5432'
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}